// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// scRate1
arma::vec scRate1(const arma::vec& T, const arma::vec& Y, const arma::vec& W, const arma::vec& T0);
RcppExport SEXP _reReg_scRate1(SEXP TSEXP, SEXP YSEXP, SEXP WSEXP, SEXP T0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type T(TSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type W(WSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type T0(T0SEXP);
    rcpp_result_gen = Rcpp::wrap(scRate1(T, Y, W, T0));
    return rcpp_result_gen;
END_RCPP
}
// sc1Log3
arma::rowvec sc1Log3(const arma::vec& a, const arma::mat& X, const arma::vec& T, const arma::vec& Y);
RcppExport SEXP _reReg_sc1Log3(SEXP aSEXP, SEXP XSEXP, SEXP TSEXP, SEXP YSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type a(aSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type T(TSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type Y(YSEXP);
    rcpp_result_gen = Rcpp::wrap(sc1Log3(a, X, T, Y));
    return rcpp_result_gen;
END_RCPP
}
// sc22
arma::rowvec sc22(const arma::vec& b, const arma::vec& R, const arma::mat& X, const arma::vec& W);
RcppExport SEXP _reReg_sc22(SEXP bSEXP, SEXP RSEXP, SEXP XSEXP, SEXP WSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type b(bSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type R(RSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type W(WSEXP);
    rcpp_result_gen = Rcpp::wrap(sc22(b, R, X, W));
    return rcpp_result_gen;
END_RCPP
}
// sc1Gehan2
arma::rowvec sc1Gehan2(const arma::vec& a, const arma::mat& X, const arma::vec& T, const arma::vec& Y);
RcppExport SEXP _reReg_sc1Gehan2(SEXP aSEXP, SEXP XSEXP, SEXP TSEXP, SEXP YSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type a(aSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type T(TSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type Y(YSEXP);
    rcpp_result_gen = Rcpp::wrap(sc1Gehan2(a, X, T, Y));
    return rcpp_result_gen;
END_RCPP
}
