## Make sure email is already validated
library(rhub)

check_for_cran()
check_on_centos()
check_on_debian()
check_on_fedora()
check_on_linux()
check_on_macos()
check_on_solaris()
check_on_ubuntu()
check_on_windows()
check_tzones()
check_with_rdevel()
check_with_roldrel()
check_with_rpatched()
check_with_rrelease()
check_with_sanitizers()
check_with_valgrind()
