# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @noRd
scRate1 <- function(T, Y, W, T0) {
    .Call('_reReg_scRate1', PACKAGE = 'reReg', T, Y, W, T0)
}

#' @noRd
sc1Log3 <- function(a, X, T, Y) {
    .Call('_reReg_sc1Log3', PACKAGE = 'reReg', a, X, T, Y)
}

#' @noRd
sc22 <- function(b, R, X, W) {
    .Call('_reReg_sc22', PACKAGE = 'reReg', b, R, X, W)
}

#' @noRd
sc1Gehan2 <- function(a, X, T, Y) {
    .Call('_reReg_sc1Gehan2', PACKAGE = 'reReg', a, X, T, Y)
}

