# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @noRd
reRate <- function(T, Y, W, T0) {
    .Call('_reReg_reRate', PACKAGE = 'reReg', T, Y, W, T0)
}

#' @noRd
reLog <- function(a, X, T, Y, W) {
    .Call('_reReg_reLog', PACKAGE = 'reReg', a, X, T, Y, W)
}

#' @noRd
re2 <- function(b, R, X, W) {
    .Call('_reReg_re2', PACKAGE = 'reReg', b, R, X, W)
}

#' @noRd
reGehan <- function(a, X, T, Y, W) {
    .Call('_reReg_reGehan', PACKAGE = 'reReg', a, X, T, Y, W)
}

#' @noRd
reGehan_s <- function(a, X, T, Y, W, nc) {
    .Call('_reReg_reGehan_s', PACKAGE = 'reReg', a, X, T, Y, W, nc)
}

#' @noRd
am1 <- function(a, T, Y, W, X, m) {
    .Call('_reReg_am1', PACKAGE = 'reReg', a, T, Y, W, X, m)
}

#' @noRd
temHaz <- function(a, b, X, Y, Z, D, W, T0) {
    .Call('_reReg_temHaz', PACKAGE = 'reReg', a, b, X, Y, Z, D, W, T0)
}

#' @noRd
temScLog <- function(a, b, X, Y, Z, D, W) {
    .Call('_reReg_temScLog', PACKAGE = 'reReg', a, b, X, Y, Z, D, W)
}

temScGehan <- function(a, b, X, Y, Z, D, W) {
    .Call('_reReg_temScGehan', PACKAGE = 'reReg', a, b, X, Y, Z, D, W)
}

temLog <- function(a, b, X, Y, Z, D, W) {
    .Call('_reReg_temLog', PACKAGE = 'reReg', a, b, X, Y, Z, D, W)
}

temGehan <- function(a, b, X, Y, Z, D, W) {
    .Call('_reReg_temGehan', PACKAGE = 'reReg', a, b, X, Y, Z, D, W)
}

